/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.grow.likes.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetLike service. Represents a row in the &quot;AssetLike&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.grow.likes.model.impl.AssetLikeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.grow.likes.model.impl.AssetLikeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetLike
 * @see com.liferay.grow.likes.model.impl.AssetLikeImpl
 * @see com.liferay.grow.likes.model.impl.AssetLikeModelImpl
 * @generated
 */
@ProviderType
public interface AssetLikeModel extends BaseModel<AssetLike> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset like model instance should use the {@link AssetLike} interface instead.
	 */

	/**
	 * Returns the primary key of this asset like.
	 *
	 * @return the primary key of this asset like
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset like.
	 *
	 * @param primaryKey the primary key of this asset like
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this asset like.
	 *
	 * @return the uuid of this asset like
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this asset like.
	 *
	 * @param uuid the uuid of this asset like
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this asset like.
	 *
	 * @return the ID of this asset like
	 */
	public long getId();

	/**
	 * Sets the ID of this asset like.
	 *
	 * @param id the ID of this asset like
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this asset like.
	 *
	 * @return the user ID of this asset like
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this asset like.
	 *
	 * @param userId the user ID of this asset like
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this asset like.
	 *
	 * @return the user uuid of this asset like
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this asset like.
	 *
	 * @param userUuid the user uuid of this asset like
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the asset entry ID of this asset like.
	 *
	 * @return the asset entry ID of this asset like
	 */
	public long getAssetEntryId();

	/**
	 * Sets the asset entry ID of this asset like.
	 *
	 * @param assetEntryId the asset entry ID of this asset like
	 */
	public void setAssetEntryId(long assetEntryId);

	/**
	 * Returns the rank of this asset like.
	 *
	 * @return the rank of this asset like
	 */
	public long getRank();

	/**
	 * Sets the rank of this asset like.
	 *
	 * @param rank the rank of this asset like
	 */
	public void setRank(long rank);

	/**
	 * Returns the create date of this asset like.
	 *
	 * @return the create date of this asset like
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset like.
	 *
	 * @param createDate the create date of this asset like
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetLike assetLike);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetLike> toCacheModel();

	@Override
	public AssetLike toEscapedModel();

	@Override
	public AssetLike toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}